name: test
on:
  push:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test1-1
        run:
          echo "aaa-1"
      - name: test1-2
        run:
          echo "aaa-2"

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run:
          echo "bbb"
