name: test
on:
  push:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test1-1
        run: |
          echo "aaa-1"
          wget https://github.com/soh335/shukujitsu/releases/download/v0.0.7/shukujitsu_0.0.7_linux_amd64.tar.gz
          tar -xvf shukujitsu_0.0.7_linux_amd64.tar.gz
          ./shukujitsu
      - name: test1-2
        run: |
          echo "aaa-2"

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run:
          echo "bbb"
