name: Assign

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  assign:
    name: assign
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: PR
        if: ${{ github.event_name == 'pull_request' }}
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Issue
        if: ${{ github.event_name == 'issues' }}
        run: gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
