name: test
on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: test
      shell: bash
      run: |
        set +e
        date
        aaa # 失敗させる
        date # ここまで到達させたい   
