name: Assign

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  assign_pull_request:
    name: Assign PR
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]'
    steps:
      - name: Assign Pull Request
        run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assign_issue:
    name: Assign Issue
    runs-on: ubuntu-latest
    if: github.actor != 'renovate[bot]'
    steps:
      - name: Assign Issue
        run: gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
